### ISSUE TITLE
forward arguments to executable

### ISSUE THREAD

**Issue by superlopuh** [DRMacIver/shrinkray#11]
This is a feature request.

In [this PR](https://github.com/xdslproject/xdsl/pull/3576), I use shrinkray to reduce a test case to a smaller reproducer. However, I needed to create a new file for this to work. This file consists of just our driver command plus some arguments:

```sh
xdsl-opt --split-input-file -p stencil-inlining --shrink
```

It would be great to be able to avoid this step, and do this to invoke shrinkray directly:
```sh
 shrinkray xdsl-opt tests/filecheck/transforms/stencil-inlining.mlir -- --split-input-file -p stencil-inlining --shrink
```

In this proposed API, all arguments after the -- are forwarded to the executable.

**Comment by DRMacIver** [comment]
I'm not against adding this, but I think right now this should just work if you pass the full command with quotes. i.e.

```
shrinkray  "xdsl-opt --split-input-file -p stencil-inlining --shrink"  tests/filecheck/transforms/stencil-inlining.mlir
```

**Comment by superlopuh** [comment]
Works like a charm! I'll let you judge whether this issue should stay open but my issue is resolved, thank you

**Comment by DRMacIver** [comment]
I think if you're happy with this solution I'll close the issue. I think the argument forwarding is probably just additional complexity without much benefit given there's already a solution here.
