### ISSUE TITLE
screen refresh

### ISSUE THREAD

**Issue by regehr** [DRMacIver/shrinkray#5]
this is obviously of no real importance whatsoever, but I'm getting a persistently corrupted screen from time to time, an easy solution might be to just wipe and redraw from scratch every now and then

![Screenshot from 2023-12-26 14-34-29](https://github.com/DRMacIver/shrinkray/assets/732536/764bcd61-37d0-4430-a1fa-2468c59216f9)

**Comment by DRMacIver** [comment]
I'm not sure how much the screen refresh is under my control (I'm fairly new to the UI library I'm using), but it's not a bad idea if I can do it!

The specific problem you're seeing though is that you pulled during a brief window before I caught some debugging prints I'd left in though, sorry. 🙈  Updating should fix it.

At some point (hopefully small number of months from now, maybe less than one) shrink ray usage will move to a more sensible development and release model so you'll deal with less random stuff I've broken, but I'm afraid this is the "work in progress" disclaimer part.
